/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import modelo.Equipos;

/**
 *
 * @author Usuario
 */
public class listaequipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form listaequipos
     */
    public listaequipos() {
        initComponents();
        llenarTabla();
        
    }

    public void llenarTabla() {
        Equipos unEquipo = new Equipos();
        DefaultTableModel tabla = (DefaultTableModel) TBLEquipos.getModel();
        Iterator<Equipos> itEqui = unEquipo.listar();
        Object[] fila = new Object[TBLEquipos.getColumnCount()];
        tabla.setRowCount(0);
        while (itEqui.hasNext()) {
            unEquipo = itEqui.next();
            fila[0] = unEquipo.getNu();
            fila[1] = unEquipo.getNomequipo();
            fila[2] = unEquipo.getMarcaequi();
            fila[3] = unEquipo.getModeloequi();
            fila[4] = unEquipo.getNoserie();
            fila[5] = unEquipo.getProveedorequi();
            fila[6] = unEquipo.getArea();
            fila[7] = unEquipo.getPlacasena();
            fila[8] = unEquipo.getContratono();
            fila[9] = unEquipo.getGarantiaequi();
            fila[10] = unEquipo.getFechacompra();
            fila[11] = unEquipo.getFechainicion();
            fila[12] = unEquipo.getAccesorios();
            fila[13] = unEquipo.getDescripcionacti();
            fila[14] = unEquipo.getEspecificaciones();
            fila[15] = unEquipo.getFuncionequi();
            fila[16] = unEquipo.getManualequi();
            fila[17] = unEquipo.getTempmax();
            fila[18] = unEquipo.getTempmin();
            fila[19] = unEquipo.getHumax();
            fila[20] = unEquipo.getHumin();
            fila[21] = unEquipo.getEnergiaequi();
            fila[22] = unEquipo.getObserequi();
            tabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLEquipos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscarlistado = new javax.swing.JTextField();
        BTNBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("Listado de equipos");
        setPreferredSize(new java.awt.Dimension(1370, 494));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reg.jpg"))); // NOI18N
        panelImage1.setPreferredSize(new java.awt.Dimension(1491, 460));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setOpaque(false);

        jScrollPane1.setOpaque(false);

        TBLEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Marca", "Modelo", "N° Serie", "Proveedor", "Ubicación", "N° Placa", "Contrato N°", "Garantía", "Fecha compra", "Fecha inicio", "Accesorios", "Descripcion actividad", "Especificaciones", "Funcion", "Manual", "T. Máxima", "T. Mínima", "H. Máxima", "H. Mínima", "Energía recomendada", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBLEquipos);

        jLabel1.setText("Buscar:");

        buscarlistado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarlistadoActionPerformed(evt);
            }
        });

        BTNBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom-icono-9136-32.png"))); // NOI18N
        BTNBuscar.setToolTipText("Buscar po N° serie");
        BTNBuscar.setContentAreaFilled(false);
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar-cancelar-icono-4935-16.png"))); // NOI18N
        jButton1.setToolTipText("Limpiar");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(buscarlistado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BTNBuscar)
                .addGap(190, 190, 190)
                .addComponent(jButton1)
                .addContainerGap(442, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(buscarlistado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNBuscar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1354, Short.MAX_VALUE)
            .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelImage1Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarlistadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarlistadoActionPerformed
        
    }//GEN-LAST:event_buscarlistadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        llenarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        llenarBusqueda(buscarlistado.getText());
    }//GEN-LAST:event_BTNBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JTable TBLEquipos;
    private javax.swing.JTextField buscarlistado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables

    private void llenarBusqueda(String busqueda) {
        Equipos unEquipo = new Equipos();
        DefaultTableModel tabla = (DefaultTableModel) TBLEquipos.getModel();
        Iterator<Equipos> itEqui = unEquipo.buscar(busqueda);
        Object[] fila = new Object[TBLEquipos.getColumnCount()];
        tabla.setRowCount(0);
        while (itEqui.hasNext()) {
            unEquipo = itEqui.next();
            
            fila[1] = unEquipo.getNomequipo();
            fila[2] = unEquipo.getMarcaequi();
            fila[3] = unEquipo.getModeloequi();
            fila[4] = unEquipo.getNoserie();
            fila[5] = unEquipo.getProveedorequi();
            fila[6] = unEquipo.getArea();
            fila[7] = unEquipo.getPlacasena();
            fila[8] = unEquipo.getContratono();
            fila[9] = unEquipo.getGarantiaequi();
            fila[10] = unEquipo.getFechacompra();
            fila[11] = unEquipo.getFechainicion();
            fila[12] = unEquipo.getAccesorios();
            fila[13] = unEquipo.getDescripcionacti();
            fila[14] = unEquipo.getEspecificaciones();
            fila[15] = unEquipo.getFuncionequi();
            fila[16] = unEquipo.getManualequi();
            fila[17] = unEquipo.getTempmax();
            fila[18] = unEquipo.getTempmin();
            fila[19] = unEquipo.getHumax();
            fila[20] = unEquipo.getHumin();
            fila[21] = unEquipo.getEnergiaequi();
            fila[22] = unEquipo.getObserequi();
            
            ((DefaultTableModel) TBLEquipos.getModel()).addRow(fila);
        }
    }
}
