/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import javax.swing.ImageIcon;
import modelo.conexion;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Felipe Rincón Sánchez
 */
public class menu extends javax.swing.JFrame implements Runnable {

    evaluacioninstalacion eva;
    validacioncon val;

    String hora, minuto, segundo, ampm;
    Thread hilo;

    Icon M = new ImageIcon(getClass().getResource("/imagenes/virus.png"));

    private static String ident;
    private static String sola;

    public static String getIdent() {
        return ident;
    }

    public static void setIdent(String ident) {
        menu.ident = ident;
    }

    public static String getSola() {
        return sola;
    }

    public static void setSola(String sola) {
        menu.sola = sola;
    }

    public static String getRol() {
        return rol;
    }

    public static void setRol(String rol) {
        menu.rol = rol;
    }
    private static String rol;

    public menu() throws ParseException {
        conexion.getInstance();
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Image icon = new ImageIcon(getClass().getResource("/imagenes/virus.png")).getImage();

        this.setIconImage(icon);
        rols.setVisible(false);
        fecha.setText(fecha());
        hilo = new Thread(this);
        hilo.start();

        login.setLocation(550, 200);
        login.setVisible(true);
        login.setSize(264, 370);
        login.setIconImage(icon);

        adsi.setIconImage(icon);

        eva = new evaluacioninstalacion();
        escritorio.add(eva);
        val = new validacioncon();
        escritorio.add(val);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JDialog();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        panelRoundTranslucido1 = new org.edisoncor.gui.panel.PanelRoundTranslucido();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        username = new org.edisoncor.gui.textField.TextFieldRound();
        password = new org.edisoncor.gui.passwordField.PasswordFieldRound();
        adsi = new javax.swing.JDialog();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        hosr = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        am = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelRound2 = new org.edisoncor.gui.panel.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adminsola = new javax.swing.JLabel();
        rols = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        usuario = new javax.swing.JMenu();
        menu1 = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenuItem();
        menu3 = new javax.swing.JMenuItem();
        menu4 = new javax.swing.JMenuItem();
        menu5 = new javax.swing.JMenuItem();
        menu6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        equipos = new javax.swing.JMenu();
        menu7 = new javax.swing.JMenuItem();
        menu10 = new javax.swing.JMenuItem();
        ambi = new javax.swing.JMenu();
        menu8 = new javax.swing.JMenuItem();
        menu9 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();

        login.setTitle("LABORATORIO DE AGUAS PARA CONSUMO HUMANO");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.setIconImage(null);
        login.setUndecorated(true);
        login.setType(java.awt.Window.Type.POPUP);

        panelImage3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logib.jpg"))); // NOI18N

        panelRoundTranslucido1.setColorDeBorde(new java.awt.Color(255, 255, 255));
        panelRoundTranslucido1.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelRoundTranslucido1.setColorSecundario(new java.awt.Color(0, 102, 102));
        panelRoundTranslucido1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAction1.setText("ENTRAR");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });
        panelRoundTranslucido1.add(buttonAction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 160, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO");
        panelRoundTranslucido1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONTRASEÑA");
        panelRoundTranslucido1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/poss.png"))); // NOI18N

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        panelRoundTranslucido1.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 22, 85, -1));

        labelMetric1.setForeground(new java.awt.Color(153, 0, 51));
        labelMetric1.setText("X");
        labelMetric1.setToolTipText("SALIR");
        labelMetric1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelMetric1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMetric1MouseClicked(evt);
            }
        });
        panelRoundTranslucido1.add(labelMetric1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 29));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        panelRoundTranslucido1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 140, 30));
        panelRoundTranslucido1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 231, 150, 30));

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        login.getAccessibleContext().setAccessibleDescription("");

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fond adsi.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo adsi.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Programando");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("El Futuro ADSI");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Desarrolladores");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Este proyecto fue diseñado");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("por el tegnólogo en ADSI de");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("la ficha 1366957 SENA VÉLEZ");

        jLabel2.setText("2018");

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(jLabel9))
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel2)))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adsiLayout = new javax.swing.GroupLayout(adsi.getContentPane());
        adsi.getContentPane().setLayout(adsiLayout);
        adsiLayout.setHorizontalGroup(
            adsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        adsiLayout.setVerticalGroup(
            adsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAB CGAO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        escritorio.setBackground(new java.awt.Color(204, 204, 204));
        escritorio.setForeground(new java.awt.Color(153, 153, 153));
        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N

        hosr.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        hosr.setForeground(new java.awt.Color(255, 255, 255));
        hosr.setText("00:00:00");

        fecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("DD/MM/YYYY");

        am.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        am.setForeground(new java.awt.Color(255, 255, 255));
        am.setText("AM");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(hosr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(am))
                    .addComponent(fecha))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hosr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(am))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fecha)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/virus.png"))); // NOI18N
        jLabel15.setToolTipText("PSSSSS CLICK AQUI");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("?");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USUARIO :");

        adminsola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminsola.setForeground(new java.awt.Color(255, 255, 255));

        rols.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rols.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(adminsola, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rols, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rols, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminsola, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        escritorio.setLayer(panelImage2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        usuario.setText("Personal");

        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-usuario-icono-4000-32.png"))); // NOI18N
        menu1.setText("Nuevo usuario");
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        usuario.add(menu1);

        menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar-icono-8221-32.png"))); // NOI18N
        menu2.setText("Fisicoquimico");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        usuario.add(menu2);

        menu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/post-message-icono-8481-32.png"))); // NOI18N
        menu3.setText("Inventario Químico");
        menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3ActionPerformed(evt);
            }
        });
        usuario.add(menu3);

        menu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portapapeles-icono-9080-32.png"))); // NOI18N
        menu4.setText("Control de Muestras");
        menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu4ActionPerformed(evt);
            }
        });
        usuario.add(menu4);

        menu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-texto-icono-8085-32.png"))); // NOI18N
        menu5.setText("Informe Resultados");
        menu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu5ActionPerformed(evt);
            }
        });
        usuario.add(menu5);

        menu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dibujo-nuevo-icono-8161-32.png"))); // NOI18N
        menu6.setText("Reactivos Químicos");
        menu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu6ActionPerformed(evt);
            }
        });
        usuario.add(menu6);

        jMenuItem1.setText("jMenuItem1");
        usuario.add(jMenuItem1);

        jMenuBar1.add(usuario);

        equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equipos.png"))); // NOI18N
        equipos.setText("Equipos");

        menu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/la-elaboracion-de-material-tableta-digitalizadora-icono-6778-32.png"))); // NOI18N
        menu7.setText("Registro");
        menu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu7ActionPerformed(evt);
            }
        });
        equipos.add(menu7);

        menu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listaaa.png"))); // NOI18N
        menu10.setText("Listado");
        menu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu10ActionPerformed(evt);
            }
        });
        equipos.add(menu10);

        jMenuBar1.add(equipos);

        ambi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guante-de-plan-de-proyecto-de-la-figura-icono-9440-48.png"))); // NOI18N
        ambi.setText("Evaluaciones");

        menu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corrector-ortografico-icono-5850-32.png"))); // NOI18N
        menu8.setText("Evaluacion de CA");
        menu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu8ActionPerformed(evt);
            }
        });
        ambi.add(menu8);

        menu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vigilar-el-cambio-icono-8152-32.png"))); // NOI18N
        menu9.setText("Evaluacion de Instalacion");
        menu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu9ActionPerformed(evt);
            }
        });
        ambi.add(menu9);

        jMenuBar1.add(ambi);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar-cancelar-icono-4935-16.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void limpiar() {
        username.setText("");
        password.setText("");
    }
    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked

    }//GEN-LAST:event_menu1MouseClicked

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        ingresar us = new ingresar();
        this.escritorio.add(us);
        us.show();
    }//GEN-LAST:event_menu1ActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        fisicoquimic fq = new fisicoquimic();
        this.escritorio.add(fq);
        fq.show();
    }//GEN-LAST:event_menu2ActionPerformed

    private void menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3ActionPerformed
        control mns = new control();
        this.escritorio.add(mns);
        mns.show();
    }//GEN-LAST:event_menu3ActionPerformed

    private void menu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu5ActionPerformed
        resultados rs = new resultados();
        this.escritorio.add(rs);
        rs.show();
    }//GEN-LAST:event_menu5ActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked

        int reply = JOptionPane.showConfirmDialog(null, "¿Está seguro de Salir?", "INICIO DE SESION ", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            login.setVisible(true);
            limpiar();
            activo();

        } else {

        }

    }//GEN-LAST:event_SalirMouseClicked

    private void menu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu6ActionPerformed
        Reactivos rc = new Reactivos();
        this.escritorio.add(rc);
        rc.show();
    }//GEN-LAST:event_menu6ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        adsi.setVisible(true);
        adsi.setSize(410, 220);
        adsi.setLocation(470, 250);

    }//GEN-LAST:event_jLabel15MouseClicked

    private void menu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu7ActionPerformed
        MenuEquipos eq = new MenuEquipos();
        this.escritorio.add(eq);
        eq.show();
    }//GEN-LAST:event_menu7ActionPerformed

    private void menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu4ActionPerformed
        CustodiasM mns = new CustodiasM();
        this.escritorio.add(mns);
        mns.show();
    }//GEN-LAST:event_menu4ActionPerformed

    private void labelMetric1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMetric1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelMetric1MouseClicked

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
        login();
    }//GEN-LAST:event_buttonAction1ActionPerformed

    private void menu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu8ActionPerformed
        // TODO add your handling code here:

        val.setVisible(true);

    }//GEN-LAST:event_menu8ActionPerformed

    private void menu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu9ActionPerformed
        // TODO add your handling code here:

        eva.setVisible(true);

    }//GEN-LAST:event_menu9ActionPerformed

    private void menu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu10ActionPerformed
        listaequipos list = new listaequipos();
        this.escritorio.add(list);
        list.show();
    }//GEN-LAST:event_menu10ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menu().setVisible(false);
                } catch (ParseException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Salir;
    private javax.swing.JLabel adminsola;
    private javax.swing.JDialog adsi;
    private javax.swing.JLabel am;
    private javax.swing.JMenu ambi;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private javax.swing.JMenu equipos;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hosr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private javax.swing.JDialog login;
    private javax.swing.JMenuItem menu1;
    private javax.swing.JMenuItem menu10;
    private javax.swing.JMenuItem menu2;
    private javax.swing.JMenuItem menu3;
    private javax.swing.JMenuItem menu4;
    private javax.swing.JMenuItem menu5;
    private javax.swing.JMenuItem menu6;
    private javax.swing.JMenuItem menu7;
    private javax.swing.JMenuItem menu8;
    private javax.swing.JMenuItem menu9;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private org.edisoncor.gui.panel.PanelRound panelRound2;
    private org.edisoncor.gui.panel.PanelRoundTranslucido panelRoundTranslucido1;
    private org.edisoncor.gui.passwordField.PasswordFieldRound password;
    private javax.swing.JLabel rols;
    private org.edisoncor.gui.textField.TextFieldRound username;
    private javax.swing.JMenu usuario;
    // End of variables declaration//GEN-END:variables
 public void login() {

        if (username.getText().length() > 0 && password.getText().length() > 0) {
            try {
                Connection con = conexion.connection;
                Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                ResultSet r = s.executeQuery("select identificacion,nombresus,usuario,rol from usuario where usuario='" + username.getText() + "' and contrasena='" + password.getText() + "' ");
                r.next();

                int encuentra = r.getRow();

                if (encuentra == 1) {
                    username.setText(r.getString("usuario"));
                    adminsola.setText(r.getString("nombresus"));
                    rols.setText(r.getString("rol"));
                    setIdent(r.getString("identificacion"));

                    setSola(username.getText());
                    setRol(rols.getText());
                    login.setVisible(false);
                    this.setVisible(true);
                    bloqueo();
                    JOptionPane.showMessageDialog(null, "Acceso concedido " + username.getText(), "INICIO DE SESION", JOptionPane.INFORMATION_MESSAGE, M);
                    limpiar();
                } else {
                    login.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Acceso Denegado!!", "INICIO DE SESION", JOptionPane.INFORMATION_MESSAGE, M);
                    limpiar();
                    login.setVisible(true);
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            login.setVisible(false);
            JOptionPane.showMessageDialog(null, "Campos vacios", "INICIO DE SESION", JOptionPane.INFORMATION_MESSAGE, M);
            limpiar();
            login.setVisible(true);

        }

    }

    public static String fecha() {
        java.util.Date fecha = new java.util.Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        return formato.format(fecha);
    }

    public void hora() {
        Calendar calendario = new GregorianCalendar();
        java.util.Date horaactual = new java.util.Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR) > 9 ? "" + calendario.get(Calendar.HOUR) : "0" + calendario.get(Calendar.HOUR);
        minuto = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundo = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "am" : "pm";
    }

    public void run() {
        Thread lola = Thread.currentThread();
        while (lola == hilo) {
            hora();
            this.hosr.setText(hora + ":" + minuto + ":" + segundo);
            this.am.setText(ampm);
        }
    }

    public void bloqueo() {
        String rolss = this.rols.getText();
        if (rolss.equals("Administrador")) {

            this.menu2.setEnabled(false);
            this.menu3.setEnabled(false);
            this.menu4.setEnabled(false);
            this.menu5.setEnabled(false);
            this.menu6.setEnabled(false);
            this.menu7.setEnabled(false);
            this.menu8.setEnabled(false);
            this.menu9.setEnabled(false);

        } else {

        }
    }

    public void activo() {
        this.menu1.setEnabled(true);
        this.menu2.setEnabled(true);
        this.menu3.setEnabled(true);
        this.menu4.setEnabled(true);
        this.menu5.setEnabled(true);
        this.menu6.setEnabled(true);
        this.menu7.setEnabled(true);
        this.menu8.setEnabled(true);
        this.menu9.setEnabled(true);
    }

}
